services:
    PM\Bundle\GermanHolidayBundle\Services\HolidayService: ~

    pm_german_holiday.services.holiday_service:
        alias: PM\Bundle\GermanHolidayBundle\Services\HolidayService
        public: true

    pm_german_holiday.twig.holiday_twig_extension:
        class: PM\Bundle\GermanHolidayBundle\Twig\HolidayTwigExtension
        tags:
            - { name: twig.extension }
